# Generated by Django 5.2.6 on 2025-09-15 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_video'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Course_Taken',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
